//! The "always exits 0" invariant, tested against the real binary.
//!
//! Every other test in this crate calls `run`, whose `-> Option<String>` signature cannot
//! express an exit code at all — so the invariant the module documentation leads with had no
//! coverage whatsoever. These tests spawn `devkit-hook` itself, which is the only way to see
//! what Claude Code sees: a non-zero exit renders as a hook *error* banner in every session.

use std::io::Write;
use std::process::{Command, Stdio};

/// Run the real binary with `args` and `stdin`, returning `(exit code, stdout)`.
fn hook(args: &[&str], stdin: &[u8]) -> (Option<i32>, String) {
  let mut child = Command::new(env!("CARGO_BIN_EXE_devkit-hook"))
    .args(args)
    // A temp dir keeps the hook away from this repo: `stop-*` would otherwise shell out to
    // git here and lint the devkit itself.
    .current_dir(std::env::temp_dir())
    .stdin(Stdio::piped())
    .stdout(Stdio::piped())
    .stderr(Stdio::null())
    .spawn()
    .expect("spawn devkit-hook");
  child.stdin.take().expect("stdin").write_all(stdin).ok();
  let out = child.wait_with_output().expect("wait");
  (out.status.code(), String::from_utf8_lossy(&out.stdout).into_owned())
}

/// The payload shapes a hook can actually be handed when something upstream goes wrong.
const MALFORMED: [&[u8]; 6] = [
  b"",
  b"not json",
  b"{",
  b"null",
  br#"{"tool_input": null}"#,
  // Invalid UTF-8: `read_to_string` fails outright and leaves the payload empty.
  &[0x7b, 0x22, 0xff, 0xfe, 0x22, 0x7d],
];

#[test]
fn every_hook_exits_zero_on_every_malformed_payload() {
  for name in [
    "pre-edit-protect",
    "pre-bash-protect-deps",
    "stop-ruff",
    "stop-pyright",
    "stop-clean",
  ] {
    for payload in MALFORMED {
      let (code, _) = hook(&[name], payload);
      assert_eq!(code, Some(0), "{name} with payload {payload:?} must exit 0");
    }
  }
}

#[test]
fn the_pre_hooks_stay_silent_on_a_malformed_payload() {
  // Silence is how a hook says "no opinion"; printing anything else would put noise into the
  // transcript for a payload it could not even read.
  for name in ["pre-edit-protect", "pre-bash-protect-deps"] {
    for payload in MALFORMED {
      let (_, stdout) = hook(&[name], payload);
      assert!(stdout.trim().is_empty(), "{name} must print nothing, got: {stdout}");
    }
  }
}

#[test]
fn an_unknown_hook_name_exits_zero() {
  // The reachable version of this is not a typo: a `.claude/settings.json` regenerated by a
  // newer devkit names a hook an older binary still on PATH has never heard of. `clap`'s
  // `parse` would exit 2 there, turning every matching tool call into a red error banner.
  for args in [&["stop-newthing"][..], &["not-a-hook"], &[]] {
    let (code, _) = hook(args, b"{}");
    assert_eq!(code, Some(0), "argv {args:?} must still exit 0");
  }
}

#[test]
fn a_deny_decision_is_one_line_of_json_on_stdout() {
  // The contract with Claude: at most one JSON object, on stdout, and exit 0 even when the
  // answer is "refuse this call".
  let (code, stdout) = hook(&["pre-edit-protect"], br#"{"tool_input":{"file_path":"/p/.env"}}"#);
  assert_eq!(code, Some(0));
  assert_eq!(stdout.lines().count(), 1, "exactly one line: {stdout}");
  let v: serde_json::Value = serde_json::from_str(stdout.trim()).expect("stdout must be JSON");
  assert_eq!(v["hookSpecificOutput"]["permissionDecision"], "deny");
}

#[test]
fn a_closed_stdout_does_not_panic() {
  // Claude killing the hook at its configured timeout, or a session interrupt, closes the
  // pipe before the decision is written. `println!` panics on that, and a panic exits 101 —
  // the hook error this crate exists to avoid.
  let mut child = Command::new(env!("CARGO_BIN_EXE_devkit-hook"))
    .args(["pre-edit-protect"])
    .current_dir(std::env::temp_dir())
    .stdin(Stdio::piped())
    .stdout(Stdio::piped())
    .stderr(Stdio::null())
    .spawn()
    .expect("spawn");
  {
    let mut stdin = child.stdin.take().expect("stdin");
    stdin.write_all(br#"{"tool_input":{"file_path":"/p/.env"}}"#).ok();
  }
  // Drop the read end before the child writes its decision.
  drop(child.stdout.take());
  let status = child.wait().expect("wait");
  assert_eq!(status.code(), Some(0), "a closed stdout must not become exit 101");
}
